version: '3.4'
services:
  vite-ngnix-app:
      stdin_open: true
      build:
          context: .
          dockerfile: Dockerfile.prod
      expose:
          - 8080
      ports:
          - "8080:80"
      environment:
          - CHOKIDAR_USEPOLLING=true